services:
  karen:
    build:
      context: .
    ports:
      - "7681:7681"
    depends_on:
      - mcp-gateway
    env_file:
      - .env
    environment:
      - GOOSE_SYSTEM_PROMPT_FILE_PATH=system.md
    models:
      qwen3:
        model_var: GOOSE_MODEL
  mcp-gateway:
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=${SERVERS}
      - --tools=${TOOLS}
      - --secrets=/run/secrets/mcp_secret
    secrets:
      - mcp_secret

models:
  qwen3:
    # pre-pull the model when starting Docker Model Runner
    model: ${MODEL}
    context_size: 16535

secrets:
  mcp_secret:
    file: ./.mcp-secrets.env
